#private key path
private_key_path=/Users/wanziliang/Desktop/wecome/private.pem

#customer secret
customer_secret=_iPO9IPZaC9vWC91wHWHZ6-zBapCfHy70_2LFRntw5k

archive_msg_secret=4H1dXpGr6IEUdYpSZJmBMMNgXwYHZ7g0fhIqNSVpuwc

#crop id
crop_id=ww918354e3468dc0cc

#api access token url
api_access_token_url=https://qyapi.weixin.qq.com/cgi-bin/gettoken

api_customer_group_details_url=https://qyapi.weixin.qq.com/cgi-bin/externalcontact/groupchat/get?access_token=%s
