spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/wxwork_archive?autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Fit2cloud!


cscrm.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
cscrm.datasource.url=jdbc:mysql://10.1.12.4:3306/jscrm?autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
cscrm.datasource.username=readonly_user
cscrm.datasource.password=Fit2cloud!

crop_id=ww92ec8bab172aa5d2
agentid=1000012
app_secret=inKbhWOPqi2YD3zWBJ8V8xEUuhIhTeyWSx2HnWHFr8w

# 登录授权的回调域名
login_redirect_uri=http://118.195.221.48:9999/wechat/work/login/callback
login_oauth2_redirect_uri=https://east.dataease.cn/wechat/work/login/oauth2-callback

#管理员id
admin_ids=WanZiLiang

cordyscrm.datasource.driver-class-name=com.mysql.jdbc.Driver
cordyscrm.datasource.url=jdbc:mysql://39.98.119.168:3406/finance_db?autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
cordyscrm.datasource.username=root
cordyscrm.datasource.password=Password123@finance_db
cordyscrm.ssh.host=39.98.119.168
cordyscrm.ssh.privateKeyPath=/opt/wxwork-tools/crm-ssh-tunnel-rsa
cordyscrm.ssh.port=22
cordyscrm.ssh.username=root
cordyscrm.ssh.local.host=127.0.0.1
cordyscrm.ssh.local.port=3307
cordyscrm.ssh.remote.host=127.0.0.1
cordyscrm.ssh.remote.port=3406